# Generated by Django 4.1.3 on 2022-11-14 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_is_staff_alter_profile_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_stuff',
        ),
    ]
