# Generated by Django 5.0.2 on 2024-03-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following_user_id',
            new_name='following_user',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user_id',
            new_name='user',
        ),
    ]
