# Generated by Django 4.1.3 on 2022-11-12 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_category_id_alter_post_id_alter_post_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='created',
            new_name='created_at',
        ),
    ]
