# Generated by Django 4.1.3 on 2022-11-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_created_post_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('publish', 'Publish')], default='draft', max_length=10, null=True, verbose_name='Status'),
        ),
    ]
