# Generated by Django 4.1.3 on 2022-11-14 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='content',
        ),
    ]
