# Generated by Django 4.1.3 on 2022-12-09 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(limit_value=100, message='Slug is over 100 letters long!')]),
        ),
    ]
